--COPY EACH SECTION OF THIS FILE INTO THE MYSQL CONSOLE TO CREATE THE DATABASE AND TABLES

-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS collab_db;
USE collab_db;


--CREATE USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('student', 'professor', 'admin') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--TO CREATE ADMIN USER REGISTER AS A USER THEN CHANGE ROLE IN THE CONSOLE



--CREATE PROJECTS TABLE